### ISSUE TITLE
Weekly task division

### ISSUE THREAD

**Issue by floorkuipers** [jvaquet/cmcb-music-learning#2]
Stephanie
- Research how people learn music: to what extent is it procedural or declarative

Jonas
- getting more familiar with ACT-R and Swift

Floor
- Making initial (paper) prototypes of idea

**Comment by jvaquet** [comment]
Lets move this to [The Project Board](https://github.com/jvaquet/cmcb-music-learning/projects/1). There we can put issues into TODO, in Progress and DONE. This makes organizing tasks easier. 
I think it's easiest to just add the tasks youre working on there. After creating a note there, you can convert it to an issue and assign who is working on it, add labels and maybe add extra information. Hope this makes sense :)
