### ISSUE TITLE
Literature

### ISSUE THREAD

**Issue by StephanieBruin** [jvaquet/cmcb-music-learning#3]
[Cognitive modelling of early music reading skill acquisition for piano_ A comparison of the Middle-C and Intervallic methods.pdf](https://github.com/jvaquet/cmcb-music-learning/files/8055329/Cognitive.modelling.of.early.music.reading.skill.acquisition.for.piano_.A.comparison.of.the.Middle-C.and.Intervallic.methods.pdf)

**Comment by jvaquet** [comment]
Moved to [Wiki](https://github.com/jvaquet/cmcb-music-learning/wiki)!
